name: Basic Integration Continues v1.0.1

on:
  pull_request:
    branches: [develop]

jobs:
  testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: eviroment
      - run: env
      - name: testing
      - run: npm i
      - run: npm test
