name: Basic Integration Continues v1.0.1
env:
  procces.env.DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
  process.env.DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
  procces.env.BACK_JWT_SECRET: ${{secrets.BACK_JWT_SECRET}}
on:
  pull_request:
    branches: [develop]

jobs:
  testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm i
      - run: npm test
